# name: Selenium PyTest CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Checkout repository
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Step 2: Set up Python
#       - name: Set up Python 3.12
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.12'

#       # Step 3: Install dependencies from requirements.txt
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       # Step 4: Install Chrome (for Selenium)
#       - name: Install Chrome
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y wget unzip chromium-browser

#       # Step 5: Create reports folder
#       - name: Create reports folder
#         run: mkdir -p reports

#       # Step 6: Run Selenium tests with Pytest and generate HTML report
#       - name: Run tests
#         run: |
#           pytest tests/ --html=reports/report.html --self-contained-html

#       # Step 7: Upload HTML report as artifact (optional)
#       - name: Upload HTML report
#         uses: actions/upload-artifact@v4
#         with:
#           name: Selenium-HTML-Report
#           path: reports/report.html

name: Selenium Python Tests

# Trigger workflow on push, PR, or manual dispatch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pytest pytest-html typing-extensions

      # 4. Install Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip gnupg
          wget -q -O google-chrome-stable_current_amd64.deb \
            https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_117.0.5938.92-1_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version

      # 5. Setup ChromeDriver automatically
      - name: Setup ChromeDriver via WebDriver Manager
        run: |
          python - <<EOF
          from selenium import webdriver
          from selenium.webdriver.chrome.service import Service
          from selenium.webdriver.chrome.options import Options
          from webdriver_manager.chrome import ChromeDriverManager

          options = Options()
          options.add_argument("--headless")
          options.add_argument("--no-sandbox")
          options.add_argument("--disable-dev-shm-usage")
          options.add_argument("--window-size=1920,1080")

          driver = webdriver.Chrome(
              service=Service(ChromeDriverManager().install()),
              options=options
          )
          driver.quit()
          EOF

      # 6. Run tests and generate HTML report
      - name: Run Selenium tests
        run: |
          mkdir -p reports
          pytest tests/ --html=reports/report.html --self-contained-html

      # 7. Upload HTML report as artifact
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: Selenium-Test-Report
          path: reports/report.html

